name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "https"

[env.vars]
CUSTOM_DOMAIN = "proxy.docker.mirror.prooo.me"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "proxy.docker.mirror.prooo.me"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.proxy.docker.mirror.prooo.me", custom_domain = true },
#   { pattern = "quay.proxy.docker.mirror.prooo.me", custom_domain = true },
#   { pattern = "gcr.proxy.docker.mirror.prooo.me", custom_domain = true },
#   { pattern = "k8s-gcr.proxy.docker.mirror.prooo.me", custom_domain = true },
#   { pattern = "k8s.proxy.docker.mirror.prooo.me", custom_domain = true },
#   { pattern = "ghcr.proxy.docker.mirror.prooo.me", custom_domain = true },
#   { pattern = "cloudsmith.proxy.docker.mirror.prooo.me", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.proxy.docker.mirror.prooo.me", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""

node_compat = true 
[build] 
command = "yarn install --mode=skip-build && yarn build"
